components:
  schemas:

    check_type_groups:
      post:
        description: >-
          Create check type group.
        summary: Create check type group
        tags:
          - Translation quality check
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - $ref: '../api_common.yaml#/components/schemas/pathParameters/accountUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/checkTypeCode'

        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountCheckTypeCreateGroupResponse'

        x-code-samples:
          - lang: curl
            source: |
              curl -X POST -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" -d "$smartlingStringTQCJSON" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/check-types/$smartlingCheckTypeCode}/groups

      get:
        description: >-
          Get check type group.
        summary: Get check type group
        tags:
          - Translation quality check
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - $ref: '../api_common.yaml#/components/schemas/pathParameters/accountUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/checkTypeCode'

        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountCheckTypeCreateGroupResponse'

        x-code-samples:
          - lang: curl
            source: |
              curl -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/check-types/$smartlingCheckTypeCode}/groups

    check_type_groups_group:
      get:
        description: >-
          Get check type group by the group identifier.
        summary: Get check type group by the group identifier
        tags:
          - Translation quality check
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - $ref: '../api_common.yaml#/components/schemas/pathParameters/accountUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/checkTypeCode'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/groupUid'

        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountCheckTypeGroupGetByUidResponse'

        x-code-samples:
          - lang: curl
            source: |
              curl -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/check-types/$smartlingCheckTypeCode}/groups/$smartlingGroupUid

      delete:
        description: >-
          Delete check type group by the group identifier.
        summary: Delete check type group by the group identifier
        tags:
          - Translation quality check
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - $ref: '../api_common.yaml#/components/schemas/pathParameters/accountUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/checkTypeCode'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/groupUid'

        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountCheckTypeGroupDeleteByUidResponse'

        x-code-samples:
          - lang: curl
            source: |
              curl -X DELETE -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/check-types/$smartlingCheckTypeCode}/groups/$smartlingGroupUid

    check_type_groups_group_locales:
      post:
        description: >-
          Add locale to group.
        summary: Add locale to group
        tags:
          - Translation quality check
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - $ref: '../api_common.yaml#/components/schemas/pathParameters/accountUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/checkTypeCode'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/groupUid'
        requestBody:
          description: ''
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountCheckTypeGroupAddLocaleRequest'

        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountCheckTypeGroupAddLocaleResponse'

        x-code-samples:
          - lang: curl
            source: |
              curl -X POST -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" -d "$smartlingStringTQCJSON" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/check-types/$smartlingCheckTypeCode/groups/$smartlingGroupUid/locales


    check_type_groups_group_locales_locale:
      delete:
        description: >-
          Delete locale from group.
        summary: Delete locale from group
        tags:
          - Translation quality check
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - $ref: '../api_common.yaml#/components/schemas/pathParameters/accountUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/checkTypeCode'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/groupUid'
          - $ref: './tqc_common.yaml#/components/schemas/pathParameters/targetLocaleId'

        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountCheckTypeGroupDeleteLocaleResponse'

        x-code-samples:
          - lang: curl
            source: |
              curl -X DELETE -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/check-types/$smartlingCheckTypeCode/groups/$smartlingGroupUid/locales/$smartlingTargetLocaleId


    AccountCheckTypeCreateGroupResponse:
      allOf:
        - $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: './tqc_common.yaml#/components/schemas/responseObjects/groupUid'
                - type: object
                  properties:
                    baseSettings:
                      allOf:
                        - $ref: './tqc_common.yaml#/components/schemas/responseObjects/severityLevelCodeResponse'
                        - $ref: './tqc_common.yaml#/components/schemas/responseObjects/checkTypeCode'
                        - type: object
                          properties:
                            subTypes:
                              type: array
                              items:
                                allOf:
                                  - $ref: './tqc_common.yaml#/components/schemas/responseObjects/checkSubTypeCodeResponse'
                                  - $ref: './tqc_common.yaml#/components/schemas/responseObjects/severityLevelCodeResponse'
                    locales:
                      type: array
                      items:
                        allOf:
                          - $ref: './tqc_common.yaml#/components/schemas/requestBodyParameter/targetLocaleId'

    AccountCheckTypeGroupGetByUidResponse:
      allOf:
        - $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: './tqc_common.yaml#/components/schemas/responseObjects/groupUid'
                - type: object
                  properties:
                    baseSettings:
                      allOf:
                        - $ref: './tqc_common.yaml#/components/schemas/responseObjects/severityLevelCodeResponse'
                        - $ref: './tqc_common.yaml#/components/schemas/responseObjects/checkTypeCode'
                        - type: object
                          properties:
                            subTypes:
                              type: array
                              items:
                                allOf:
                                  - $ref: './tqc_common.yaml#/components/schemas/responseObjects/checkSubTypeCodeResponse'
                                  - $ref: './tqc_common.yaml#/components/schemas/responseObjects/severityLevelCodeResponse'
                    locales:
                      type: array
                      items:
                        allOf:
                          - $ref: './tqc_common.yaml#/components/schemas/requestBodyParameter/targetLocaleId'

    AccountCheckTypeGroupDeleteByUidResponse:
      allOf:
        - $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: './tqc_common.yaml#/components/schemas/responseObjects/groupUid'

    AccountCheckTypeGroupAddLocaleRequest:
      allOf:
        - $ref: './tqc_common.yaml#/components/schemas/requestBodyParameter/targetLocaleId'

    AccountCheckTypeGroupAddLocaleResponse:
      allOf:
        - $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: './tqc_common.yaml#/components/schemas/requestBodyParameter/targetLocaleId'

    AccountCheckTypeGroupDeleteLocaleResponse:
      allOf:
        - $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: './tqc_common.yaml#/components/schemas/requestBodyParameter/targetLocaleId'

